force-app/main/default/objects/Audit_Log__c/Audit_Log__c.object-meta.xml
<CustomObject>
    <label>Audit Log</label>
    <nameField>
        <displayFormat>LOG-{0000}</displayFormat>
        <label>Nombre de Audit Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Audit_Log__c/fields/Acci_n_realizada__c.field-meta.xml
<CustomField>
    <fullName>Acci_n_realizada__c</fullName>
    <label>Acción realizada</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Audit_Log__c/fields/Datos_nuevos__c.field-meta.xml
<CustomField>
    <fullName>Datos_nuevos__c</fullName>
    <label>Datos nuevos</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Audit_Log__c/fields/Datos_previos__c.field-meta.xml
<CustomField>
    <fullName>Datos_previos__c</fullName>
    <label>Datos previos</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Audit_Log__c/fields/Fecha_Modificacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Modificacion__c</fullName>
    <label>Fecha Modificacion</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Audit_Log__c/fields/Id_registro__c.field-meta.xml
<CustomField>
    <fullName>Id_registro__c</fullName>
    <label>Id registro</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/debugging_of_quotes__mdt/debugging_of_quotes__mdt.object-meta.xml
<CustomObject>
    <label>debugging of quotes</label>
    <pluralLabel>debugging of quotes</pluralLabel>
</CustomObject>

force-app/main/default/objects/debugging_of_quotes__mdt/fields/Dias__c.field-meta.xml
<CustomField>
    <fullName>Dias__c</fullName>
    <inlineHelpText>Dias de antigüedad de las cotizaciones para la depuracion</inlineHelpText>
    <label>Dias</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/debugging_of_quotes__mdt/fields/Nombre_de_accion_de_log__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_accion_de_log__c</fullName>
    <label>Nombre de accion de log</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DebuggingQuotes_bch.cls
global class DebuggingQuotes_bch implements Database.Batchable<SObject>, Database.Stateful {
    
    global debugging_of_quotes__mdt Metadata = [SELECT Id,Dias__c,Nombre_de_accion_de_log__c,DeveloperName FROM debugging_of_quotes__mdt WHERE DeveloperName = 'Depuracion_Quotes'];
    private Integer recordsProcessed = 0;
    private Integer recordsDeleted = 0;
    
    global  List<Audit_Log__c> Logs = New List<Audit_Log__c>();
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        
        DateTime retentionDate = System.now().addDays(-integer.valueof(Metadata.Dias__c));
        
        String strQuery = 
            'SELECT Id, Name, Status, CreatedDate ' +
            'FROM Quote ' +
            'WHERE Status = \'Rechazado\' ' +
            'AND CreatedDate <= :retentionDate';
        
        return Database.getQueryLocator(strQuery);
    }
    
    global void execute(Database.BatchableContext bc, List<Quote> records) {
        recordsProcessed += records.size();
        
        Database.DeleteResult[] results = Database.delete(records, false);
        
        for (Database.DeleteResult result : results) {
            
            if (result.isSuccess()) {
                recordsDeleted++;
            } else {
                
                for (Database.Error error : result.getErrors()) {   
                    AddlogError(String.valueof(error.getFields()),result.getId(), error.getStatusCode()+error.getMessage());
                }
            }
        }
        AddlogError('Procesadas: ' + recordsProcessed +'|| Eliminadas: ' + recordsDeleted, 'Eliminados',null );
    }
    
    global void finish(Database.BatchableContext bc) {
        if (!Logs.isEmpty()) {
            insert Logs;
        }
    }
    
    public void AddlogError(String Datos ,String Id,String Fallo){
        Logs.add(
            New Audit_Log__c(
                Acci_n_realizada__c = 'ERROR '+ Metadata.Nombre_de_accion_de_log__c,
                Datos_previos__c =  Datos,
                Datos_nuevos__c = Fallo, 
                Fecha_Modificacion__c = System.now(),
                Id_registro__c = Id
            ));
    }
}