force-app/main/default/objects/Audit_Log__c/Audit_Log__c.object-meta.xml
<CustomObject>
    <label>Audit Log</label>
    <nameField>
        <displayFormat>LOG-{0000}</displayFormat>
        <label>Nombre de Audit Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Audit_Log__c/fields/Acci_n_realizada__c.field-meta.xml
<CustomField>
    <fullName>Acci_n_realizada__c</fullName>
    <label>Acción realizada</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Audit_Log__c/fields/Datos_nuevos__c.field-meta.xml
<CustomField>
    <fullName>Datos_nuevos__c</fullName>
    <label>Datos nuevos</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Audit_Log__c/fields/Datos_previos__c.field-meta.xml
<CustomField>
    <fullName>Datos_previos__c</fullName>
    <label>Datos previos</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Audit_Log__c/fields/Fecha_Modificacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Modificacion__c</fullName>
    <label>Fecha Modificacion</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Audit_Log__c/fields/Id_registro__c.field-meta.xml
<CustomField>
    <fullName>Id_registro__c</fullName>
    <label>Id registro</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Numero_de_versiones_de_presupuesto__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_versiones_de_presupuesto__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Numero de versiones de presupuesto</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/VersionKey__c.field-meta.xml
<CustomField>
    <fullName>VersionKey__c</fullName>
    <label>VersionKey</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/OpportunityHelperTest.cls
@IsTest
private class OpportunityHelperTest {
    
    @TestSetup
    static void setupData() {
        
        Opportunity opp = new Opportunity(
            Name = 'Test Opportunity',
            StageName = 'Prospecting',
            CloseDate = Date.today()
        );
        
        insert opp;
        
        
        
        Quote quote1 = new Quote(
            Name = 'Quote Test 1',
            OpportunityId = opp.Id,
            VersionKey__c = opp.Id + '1',
            Status = 'Borrador'
        );
        insert quote1;
        quote1 = new Quote(
            Name = 'Quote Test 2',
            OpportunityId = opp.Id,
            VersionKey__c = opp.Id + '2',
            Status = 'Borrador'
        );
        opp.Numero_de_versiones_de_presupuesto__c = 1;
        Update opp;
        insert quote1;
        quote1 = new Quote(
            Name = 'Quote Test 3',
            OpportunityId = opp.Id,
            VersionKey__c = opp.Id + '2',
            Status = 'Borrador'
        );
        opp.Numero_de_versiones_de_presupuesto__c = 2;
        Update opp;
        insert quote1;
    }
    
    
    @IsTest
    static void testRechazarCotizaciones() {
        Opportunity opp = [
            SELECT Id, SyncedQuoteId
            FROM Opportunity
            LIMIT 1
        ];
        List<Quote> quotes = [
            SELECT Id, OpportunityId, Status
            FROM Quote
            WHERE OpportunityId = :opp.Id
            ORDER BY CreatedDate ASC
        ];
        Quote quoteGanadora = quotes[0];
        
        Test.startTest();
        
        opp.SyncedQuoteId = quoteGanadora.Id;
        update opp;
        
        Test.stopTest();
        
        quotes = [
            SELECT Id, OpportunityId, Status
            FROM Quote
            WHERE OpportunityId = :opp.Id
            ORDER BY CreatedDate ASC
        ];
        
        List<Audit_Log__c> auditLogs = [
            SELECT Id,
            Acci_n_realizada__c,
            Datos_previos__c,
            Datos_nuevos__c,
            Fecha_Modificacion__c,
            Id_registro__c
            FROM Audit_Log__c
            WHERE Id_registro__c IN :new Set<Id>{
                quotes[1].Id,
                    quotes[2].Id
                    }
        ];
    }
    
    
    @IsTest
    static void testNoRechazarCotizacionesSinSincronizar() {
        
        Opportunity opp = [
            SELECT Id, SyncedQuoteId
            FROM Opportunity
            LIMIT 1
        ];
        
        Test.startTest();
        opp.Name = 'Opportunity Updated';
        update opp;
        
        Test.stopTest();
        
        List<Quote> quotes = [
            SELECT Id, Status
            FROM Quote
            WHERE OpportunityId = :opp.Id
        ];
        
        List<Audit_Log__c> auditLogs = [
            SELECT Id
            FROM Audit_Log__c
            WHERE Id_registro__c IN :new Set<Id>{
                quotes[0].Id,
                    quotes[1].Id,
                    quotes[2].Id
                    }
        ];
        
    }
}