force-app/main/default/objects/Audit_Log__c/Audit_Log__c.object-meta.xml
<CustomObject>
    <label>Audit Log</label>
    <nameField>
        <displayFormat>LOG-{0000}</displayFormat>
        <label>Nombre de Audit Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Audit_Log__c/fields/Acci_n_realizada__c.field-meta.xml
<CustomField>
    <fullName>Acci_n_realizada__c</fullName>
    <label>Acción realizada</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Audit_Log__c/fields/Datos_nuevos__c.field-meta.xml
<CustomField>
    <fullName>Datos_nuevos__c</fullName>
    <label>Datos nuevos</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Audit_Log__c/fields/Datos_previos__c.field-meta.xml
<CustomField>
    <fullName>Datos_previos__c</fullName>
    <label>Datos previos</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Audit_Log__c/fields/Fecha_Modificacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Modificacion__c</fullName>
    <label>Fecha Modificacion</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Audit_Log__c/fields/Id_registro__c.field-meta.xml
<CustomField>
    <fullName>Id_registro__c</fullName>
    <label>Id registro</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpportunityHelper.cls
/**
* ------------------------------------------------------------------------------------------------
* @Name     OpportunityHelper
* @Author   Daniel Jaimes
* @Date     06 Septiembre 2026
* -----------------------------------------------------------------------------------------------
* @Description Class "Class helper Responsible for rejecting quotes that were not accepted"
* -----------------------------------------------------------------------------------------------
* @Changes
* 
* -----------------------------------------------------------------------------------------------
*/
public class OpportunityHelper {
    
    public static void rechazarCotizaciones(Set<Id> opportunityIds) {
        
        List<Quote> quotesToUpdate = new List<Quote>();
        List<Audit_Log__c> auditLogs = new List<Audit_Log__c>();
        Set<Id> syncedQuoteIds = new Set<Id>();
        
        for (Opportunity opp : [SELECT Id, SyncedQuoteId FROM Opportunity
                                WHERE Id IN :opportunityIds AND SyncedQuoteId != null]) {
                                    syncedQuoteIds.add(opp.SyncedQuoteId);
                                }
        
        for (Quote quote : [SELECT Id,OpportunityId,Status FROM Quote
                            WHERE OpportunityId IN :opportunityIds AND Id NOT IN :syncedQuoteIds
                           ]) {
                               
                               if (quote.Status != 'Rechazado') {
                                   
                                   String estadoAnterior = quote.Status;
                                   quote.Status = 'Rechazado';
                                   quotesToUpdate.add(quote);
                                   
                                   
                                   Audit_Log__c audit = new Audit_Log__c();
                                   audit.Acci_n_realizada__c = label.Audit_Log_update_status_quote;
                                   audit.Datos_previos__c =    'Estado: ' + estadoAnterior;
                                   audit.Datos_nuevos__c =     'Estado: ' + quote.Status;
                                   audit.Fecha_Modificacion__c = System.now();
                                   audit.Id_registro__c = quote.Id;
                                   auditLogs.add(audit);
                               }
                           }
        if (!quotesToUpdate.isEmpty()) {
            update quotesToUpdate;
            if (!auditLogs.isEmpty()) {
                insert auditLogs;
            }
        }
    }
}